### ISSUE TITLE
Part Two CSS

### ISSUE THREAD

**Issue by bgarrison25** [existdissolve/CarTracker#1]
First off in part two you don't say anything about creating CSS for the car image. Secondly you don't provide the car image in your tutorial. When copying the image I found in the git repository and using it, there is a blue border around it and it doesn't work well with the title. 

I then went into your github code and found that you had CSS. Two things. A) the css has an error. In the first line you have "ont-weight" instead of "font-weight". B) You don't explain anywhere in your tutorial on how to include this css. That would be very helpful to beginnners. 

Edit: I added the CSS you have in resources / css and it does NOT work. The header floats underneath the picture and isn't visible and the car picture is smaller and still has a border around it.

Thanks!

**Comment by existdissolve** [comment]
@bgarrison25 -- Thanks for the feedback! I've fixed the typo in the CSS.

Re: the CSS file, did you use the one from Part Two, or from one of the other parts? It's possible that the CSS for Part Two isn't complete...when I started this, I wasn't intending to break it up into parts like I ultimately did, so there's a decent chance that some parts are missing. I'll try to troubleshoot it later today and get back with you.

Thanks!

**Comment by bgarrison25** [comment]
The CSS I used was from part two. Some of my old CSS was cached....and for the most part it works now...however it still has a blue border around it. I believe it has something to do with PNG's but I havent been able to figure it out.

**Comment by bgarrison25** [comment]
I figured it out. partially. The header panel has a border around it and it isn't taking up the entire width. Im going to mess around with some CSS and see what I can do about it. Unless there is a way to remove the panel border in ExtJs?

**Comment by existdissolve** [comment]
You could try adding border: false to the panel config.

On Wed, Oct 2, 2013 at 9:53 AM, bgarrison25 notifications@github.comwrote:

> I figured it out. partially. The header panel has a border around it and
> it isn't taking up the entire width. Im going to mess around with some CSS
> and see what I can do about it. Unless there is a way to remove the panel
> border in ExtJs?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/existdissolve/CarTracker/issues/1#issuecomment-25545176
> .

## 

The only thing we learn from history is that we learn nothing from history.

http://singularityconcepts.com

**Comment by bgarrison25** [comment]
`items: [{
            region: 'north',
            border: false,
            xtype: 'panel',
            // hbox layout will distribute items horizontally within this container
            // so if we ever want to add a menu on the right (or something else), it will be easy
            layout: 'hbox',
            // adding an item to contain the title and logo of our app
            items: [
                {
                    xtype: 'panel',
                    border: false,
                    bodyPadding: 5,
                    html: '<img src="resources/images/car.png" /><h1>Car Tracker</h1>',
                    cls: 'header'
                }
            ]`

This worked

**Comment by bgarrison25** [comment]
Thanks for the quick responses. I'm going through the whole tutorial so ill let you know if I see anything else.

**Comment by bgarrison25** [comment]
Im going to close this issue....but id recommend adding the fixed css and the border:false config into the part Two (and future parts) code. :+1:

**Comment by existdissolve** [comment]
Would you be able to submit a pull request for this?

On Wed, Oct 2, 2013 at 10:06 AM, bgarrison25 notifications@github.comwrote:

> Im going to close this issue....but id recommend adding the fixed css and
> the border:false config into the part Two (and future parts) code. [image:
> :+1:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/existdissolve/CarTracker/issues/1#issuecomment-25546355
> .

## 

The only thing we learn from history is that we learn nothing from history.

http://singularityconcepts.com

**Comment by bgarrison25** [comment]
I would love to but I came to realize that the finalized code (after the refactoring) was all correct. The only update would be in the tutorial that I was following. The pre-refactored code was putting the header in a panel which has a border. The refactored code does not. Also, a quick mention about getting the images / css from your code repo and a quick comment about how to add style.css to index.html might be helpful to future followers of the tutorial.

**Comment by existdissolve** [comment]
Ah, gotcha. I will add those notes later today. Thanks again!

On Wed, Oct 2, 2013 at 11:53 AM, bgarrison25 notifications@github.comwrote:

> I would love to but I came to realize that the finalized code (after the
> refactoring) was all correct. The only update would be in the tutorial that
> I was following. The pre-refactored code was putting the header in a panel
> which has a border. The refactored code does not. Also, a quick mention
> about getting the images / css from your code repo and a quick comment
> about how to add style.css to index.html might be helpful to future
> followers of the tutorial.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/existdissolve/CarTracker/issues/1#issuecomment-25555666
> .

## 

The only thing we learn from history is that we learn nothing from history.

http://singularityconcepts.com
